apps/appAsignaturaDocente/urls.py
from django.conf.urls import url
from .views import (asignaturaxdocente,listarasignatura,
                    listardocentes,eliminarasignaturaxdocente,eliminarDocentexAsignatura,
                    listadeAsignatura, listaAlumnos, listadeclases, addclase,
                    asistencia, evaluacion, nota
                    )


urlpatterns = [
    url(r'^asignaturadocente/asignaturaxdocente$', asignaturaxdocente),
    url(r'^asignaturadocente/asignaturaxdocente/listardocentes', listardocentes),
    url(r'^asignaturadocente/asignaturaxdocente/listarasignaturas$', listarasignatura),
    url(r'^asignaturadocente/asignaturaxdocente/eliminar$', eliminarasignaturaxdocente),
    url(r'^asignaturadocente/SemestrexDocente/eliminar$', eliminarDocentexAsignatura),

    url(r'^gestionasignatura/listaAsignatura$', listadeAsignatura),
    url(r'^gestionasignatura/listaAlumnos', listaAlumnos),
    url(r'^gestionasignatura/listadeclases', listadeclases),
    url(r'^gestionasignatura/addClase', addclase),
    url(r'^gestionasignatura/asistencia', asistencia),
    url(r'^gestionasignatura/evaluacion$', evaluacion),
    url(r'^gestionasignatura/nota$', nota),

]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.security.urls')),
    url(r'^', include('apps.Sistema_Aplicacion.urls')),
    url(r'^', include('apps.appmatricula.urls')),
    url(r'^', include('apps.appAsignaturaDocente.urls')),
    url(r'^', include('apps.appReporte.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Sistema_Aplicacion/models.py
from django.db import models
from apps.security.models import Users

# Create your models here.

class Asignatura (models.Model):
    Nombre          =models.CharField(max_length=50)
    Creditos        =models.IntegerField(default=0)
    Estado          =models.BooleanField(default=True)

    def __str__(self):
        return self.Nombre
    class Meta:
        db_table ="Asignatura"

class Semestre (models.Model):
    Anio_semestre               =models.CharField(max_length=50)
    Descripcion                 =models.CharField(max_length=60)
    Estado                      =models.BooleanField(default=True)
    #asignatura                  =models.ManyToManyField(Asignatura, through='AsignaturaxDocente')
    docente                     =models.ManyToManyField(Users, through='SemestrexDocente')
    def __str__(self):
        return self.Anio_semestre
    class Meta:
        db_table ="Semestre"


class SemestrexDocente(models.Model):
    idAsignatura          = models.ManyToManyField(Asignatura, through='DocentexAsignatura')
    idDocente              = models.ForeignKey(Users,verbose_name='Docente', null=True)
    idSemestre             = models.ForeignKey(Semestre,verbose_name='Semestre')
    Estado                 = models.BooleanField(default=True)
    class Meta:
        db_table ="SemestrexDocente"

class DocentexAsignatura(models.Model):
    TipoEnsenianza         = models.CharField(max_length=30, null=True)
    idSemestrexDocente   = models.ForeignKey(SemestrexDocente)
    idAsignatura           = models.ForeignKey(Asignatura)
    Estado                 = models.BooleanField(default=True)
    class Meta:
        db_table ="DocentexAsignatura"

class Aula (models.Model):
    Descripcion              =models.CharField(max_length=30,verbose_name='Aula')
    asignaturadocente        =models.ManyToManyField(DocentexAsignatura, through="Clases")
    Estado                   =models.BooleanField(default=True)
    def __str__(self):
        return str(self.Descripcion)
    class Meta:
        db_table ="Aula"

class Clases(models.Model):
    Tema                                =models.CharField(max_length=50)
    Descripcion                         =models.CharField(max_length=100)
    fecha                               =models.DateField()
    Estado                              =models.BooleanField(default=True)
    idDocentexAsignatura                =models.ForeignKey(DocentexAsignatura)
    idAula                              =models.ForeignKey(Aula)
    def __str__(self):
        return self.Tema
    class Meta:
        db_table ="Clases"


class Matriculados (models.Model):
    codMatricula        =models.CharField(max_length=8, null=True, blank=True)
    idAlumno            =models.ForeignKey(Users,verbose_name='Alumno', null=True)
    idDocentexAsignatura   =models.ForeignKey(DocentexAsignatura)
    Estado              =models.BooleanField(default=True)
    clase               =models.ManyToManyField(Clases,through='Asistencia',related_name="fk_Asistencia")
    #evaluacion          =models.ManyToManyField(Clases,through='Evaluacion',related_name="fk_Evaluacion")
    def __str__(self):
        return self.codMatricula
    class Meta:
        db_table ="Matriculados"

class Asistencia (models.Model):
    idmatriculados = models.ForeignKey(Matriculados)
    idclases       = models.ForeignKey(Clases)
    fecha          = models.DateTimeField(auto_now_add=True)
    Estado              =models.BooleanField(default=True)
    class Meta:
        db_table ="Asistencia"


class Evaluacion (models.Model):
    primerapractica  =models.IntegerField(default=0)
    segundapractica  =models.IntegerField(default=0)
    primerparcial    =models.IntegerField(default=0)
    segundoparcial   =models.IntegerField(default=0)
    trabajos         =models.IntegerField(default=0)
    idmatriculados   = models.ForeignKey(Matriculados)

    class Meta:
        db_table ="Evaluacion"

apps/appAsignaturaDocente/models.py
from django.db import models

# Create your models here.

apps/appAsignaturaDocente/forms.py
from django import forms
from apps.Sistema_Aplicacion.models import Clases

class formClase(forms.ModelForm):
    class Meta():
        model = Clases
        filter = ['Tema','Descripcion','fecha','idDocentexAsignatura','idAula' ]
        exclude = ('Estado',)
        widgets = {
            'Tema' : forms.TextInput(attrs={'class': 'form-control input-sm', 'placeholder' : 'Ingrese Tema'}),
            'Descripcion' : forms.Textarea(attrs={'class': 'form-control input-sm', 'placeholder' : 'Ingrese su Descripcion'}),
            'fecha' : forms.DateInput(attrs={'class': 'form-control input-sm', 'type' : 'date'}),
            'idDocentexAsignatura' : forms.HiddenInput(),
        }

apps/appAsignaturaDocente/views.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseBadRequest
from apps.Sistema_Aplicacion.models import (Asistencia,Clases, Matriculados, DocentexAsignatura,
                                            Semestre, SemestrexDocente, Asignatura, Evaluacion,)
from apps.security.models import Users
from .forms import formClase
import json

# Create your views here.
def asignaturaxdocente(r):
    template_name = "listasemestredocente.html"
    d = Semestre.objects.filter(Estado=True).order_by('-id')
    p = {'semestre':d}
    return render(r,template_name,p)

def listarasignatura(r):
    if r.method =="POST":
        s = DocentexAsignatura.objects.filter(idAsignatura_id=int(r.POST.get('idasignatura')),
                                              idSemestrexDocente_id=int(r.POST.get('idsemestredocente')), Estado=True)
        if s:
            msm ="ya se encuentra guardado"
            return HttpResponseBadRequest(msm)
        else:
            DocentexAsignatura(idAsignatura_id=int(r.POST.get('idasignatura')),idSemestrexDocente_id=int(r.POST.get('idsemestredocente'))).save()
            msm ="guardado correctamente"
            return HttpResponse(msm)

    else:
        template_name = "listaraAsignatura.html"
        id = int(r.GET.get("id"))
        idd = int(r.GET.get("iddocente"))
        ids = int(r.GET.get("ids"))
        docente = Users.objects.filter(status=True, profiles=11)
        asig    = Asignatura.objects.filter(Estado=True)
        d = DocentexAsignatura.objects.filter(Estado=True,idSemestrexDocente_id =id).values(
            'idAsignatura__Nombre','id','idAsignatura__Creditos','idAsignatura_id'
        )
        p = {'asignaturas':asig,'semestredocente':id,'DocentexAsignatura':d,'nombredocente':docente,'ids':ids}
        return render(r,template_name,p)
def listardocentes(r):
    if r.method =="POST":
        s = SemestrexDocente.objects.filter(idDocente_id=int(r.POST.get('iddocente')),idSemestre_id=int(r.POST.get('idsemestre')), Estado=True)
        if s:
            msm ="ya se encuentra guardado"
            return HttpResponseBadRequest(msm)
        else:
            SemestrexDocente(idDocente_id=int(r.POST.get('iddocente')),idSemestre_id=int(r.POST.get('idsemestre'))).save()
            msm ="guardado correctamente"
            return HttpResponse(msm)

    else:
        template_name = "listaradocente.html"
        idd = int(r.GET.get("idsemestre"))
        semestre = Semestre.objects.filter(id=idd)
        docentes = Users.objects.filter(status=True, profiles=11)
        d = SemestrexDocente.objects.filter(Estado=True,idSemestre=idd, idDocente__profiles=11).values('id',
            'idDocente__names','idDocente__first_name','idDocente__last_name','idDocente_id'
        )
        p = {'docentes':docentes,'SemestrexDocente':d,'nombresemestre':semestre}
        return render(r,template_name,p)

def eliminarasignaturaxdocente(r):
    idd = int(r.GET.get('iddd'))
    e = SemestrexDocente.objects.get(pk = idd)
    e.Estado = False
    e.save()
    return HttpResponse("eliminado correctamente")

def eliminarDocentexAsignatura(r):
    idd = int(r.GET.get('iddd'))
    e = DocentexAsignatura.objects.get(pk = idd)
    e.Estado = False
    e.save()
    return HttpResponse("eliminado correctamente")



### lista de  las asignaturas que fueron asiganadas al deocente+++

def listadeAsignatura(r):
    ids = Semestre.objects.filter(Estado=True).order_by('-id')[:1].values('id')
    idu = r.user.id
    d = DocentexAsignatura.objects.filter(Estado=True,idSemestrexDocente__idSemestre =ids,
                                          idSemestrexDocente__idDocente_id=idu).values(
            'idAsignatura__Nombre','id','idAsignatura__Creditos','idAsignatura_id'
        )
    template_name="cursosdeldocente.html"
    p = {'cursos':d}
    return render(r,template_name,p)

def listaAlumnos(r):
    d = Matriculados.objects.filter(Estado=True,
                                    idDocentexAsignatura_id =int(r.GET.get('id'))).values(
            'idAlumno__names','id','idAlumno__first_name',
        'idAlumno__last_name', 'idAlumno__dni'
        )

    template_name="alumnosdeldocente.html"
    p = {'alumnos':d}
    return render(r,template_name,p)

def listadeclases(r):
    d = Clases.objects.filter(Estado=True,
            idDocentexAsignatura_id =int(r.GET.get('id'))).values(
            'Tema','id','Descripcion',
            'fecha', 'idAula__Descripcion'
        )

    template_name="listadeclases.html"
    p = {'clases':d,'iddoc':r.GET.get('id')}
    return render(r,template_name,p)

def addclase(r):
    if r.method =='GET':
            f = formClase()
            t = "REGISTRAR"
            return render(r,"formularioClase.html",{'tipo':t,'formulario':f,'iddoc':r.GET.get('iddoc')})
    else:
        f =formClase(r.POST)

        if f.is_valid():
            f.save()
            return HttpResponse("Guardado correctamente")
        else:
            ee ={}
            for i in f.error:
                e =f.errors[i]
                ee[i] = str(e)
            return HttpResponseBadRequest(json.dumps(ee))

def asistencia(r):
    d = Asistencia.objects.filter(Estado=True,
                                    idclases_id =int(r.GET.get('id'))).values(
            'idmatriculados__idAlumno__names','id','idmatriculados__idAlumno__first_name',
        'idmatriculados__idAlumno__last_name', 'idmatriculados__idAlumno__dni'
        )

    template_name="listaasistencia.html"
    p = {'asistencia':d,'idc':r.GET.get('idc')}
    return render(r,template_name,p)

def evaluacion(r):
    d = Matriculados.objects.filter(Estado=True,
                                    idDocentexAsignatura_id =int(r.GET.get('id'))).values(
            'idAlumno__names','id','idAlumno__first_name','idAlumno_id',
        'idAlumno__last_name', 'idAlumno__dni'
        )

    evv = Evaluacion.objects.filter(idmatriculados__idDocentexAsignatura=int(r.GET.get('id')))
    if not evv:
        for i in d:
            ee = Evaluacion()
            ee.idmatriculados_id = i["id"]
            ee.save()
    evv = Evaluacion.objects.filter(idmatriculados__idDocentexAsignatura=int(r.GET.get('id')))

    eva = []
    for i in d:
        for j in evv:
            if i["id"] == j.idmatriculados_id:
                eva.append({
                    'id': j.id,
                    'idAlumno__names' : i["idAlumno__names"],
                    'idAlumno__first_name' : i["idAlumno__first_name"],
                    'idAlumno__last_name'  : i["idAlumno__last_name"],
                    'idAlumno__dni'        : i["idAlumno__dni"],
                    'primerapractica'      : j.primerapractica,
                    'segundapractica'      : j.segundapractica,
                    'primerparcial'      : j.primerparcial ,
                    'segundoparcial'      : j.segundoparcial,
                    'trabajos'      : j.trabajos,
                    'notafinal'      : float(j.primerapractica *  0.15 + j.segundapractica *  0.15 + j.primerparcial *  0.25 + j.segundoparcial *  0.25 + j.trabajos *  0.20),
                })
    template_name="evaluacion.html"
    p = {'eva':eva,'idd':r.GET.get('id')}
    return render(r,template_name,p)

def nota(r):
    eval("Evaluacion.objects.filter(id = "+str(r.GET.get("id"))+").update("+r.GET.get("n")+" = "+str(r.GET.get("nota"))+")")
    return HttpResponse("actualizado")

apps/appAsignaturaDocente/templates/alumnosdeldocente.html
    <i class="puntero fa fa-arrow-left "
       onclick="traemedatos('gestionasignatura/listaAsignatura')"
       style="color: red">Atras
    </i>
<b>
    <h2 align="center" style="color: #00a792"> Lista de Alumnos del curso</h2>
</b>

<table class="table table-condensed">
    <thead>
      <tr>
        <th>N°</th>
        <th>Código</th>
        <th>Apellidos y Nombres</th>
      </tr>
    </thead>
    <tbody>
    {% for a in alumnos %}
      <tr>
          <td>{{forloop.counter}}</td>
          <td>
              {{a.idAlumno__dni}}
          </td>
          <td>
              {{a.idAlumno__first_name}} {{a.idAlumno__last_name}}, {{a.idAlumno__names}}
          </td>
      </tr>
    {% endfor %}
    </tbody>
</table>

apps/appAsignaturaDocente/templates/cursosdeldocente.html
<b><h2 align="center" style="color: #00a792">Lista de los cursos de Docentes</h2></b><br>
{% for a in cursos %}
    <div class="infographic-box merged merged-top merged-right pull-left curso" onclick="curso(this,'i{{a.idAsignatura_id}}')">
        <i class="fa fa-book green-bg"></i>
        <span class="label label-primary label-circle">
            {{a.idAsignatura__Creditos}}
        </span>  Créditos
        <input type="hidden" name="idcurso[]" id="i{{a.idAsignatura_id}}" disabled value="{{a.idAsignatura_id}}"/>
            <span class="value green">{{a.idAsignatura__Nombre|title}}</span>
            <span class="headline">
                <a href="#" onclick="veralumnos({{a.id}})" ><i  style="color: #00b29c"></i> Ver alumnos </a><br>
                <a href="#" onclick="verclases({{a.id}})"><i  style="color: #00b29c"></i> Ver Clases </a><br>
                <a href="#" onclick="vereva({{a.id}})"><i  style="color: #00b29c"></i> Ver Evaluación </a>
            </span>
    </div>
{% endfor %}

<script>
    function veralumnos(id){
        $.get('gestionasignatura/listaAlumnos?id='+id).done(function(r){
            $("#resultados").empty().html(r);
        });

    }
    function vereva(id){
        $.get('gestionasignatura/evaluacion?id='+id).done(function(r){
            $("#resultados").empty().html(r);
        });

    }
    function verclases(id){
        $.get('gestionasignatura/listadeclases?id='+id).done(function(r){
            $("#resultados").empty().html(r);
        });

    }
</script>

apps/appAsignaturaDocente/templates/evaluacion.html
<style>
    input{
        border: none;
    }
</style>
<i class="puntero fa fa-arrow-left "
       onclick="traemedatos('gestionasignatura/listaAsignatura')"
       style="color: red">Atras
    </i>
<b>
    <h2 align="center" style="color: #00a792"> Evaluación de los Alumnos del curso</h2>
</b>

<table class="table table-condensed">
    <thead>
      <tr>
        <th>N°</th>
        <th>Código</th>
        <th>Apellidos y Nombres</th>
          <th>p1</th>
          <th>p2</th>
          <th>pp</th>
          <th>sp</th>
          <th>Trabajos</th>
          <th>Nota final</th>
      </tr>
    </thead>
    <tbody>
    {% for a in eva %}
      <tr>
          <td>{{forloop.counter}}</td>
          <td>
              {{a.idAlumno__dni}}
          </td>
          <td>
              {{a.idAlumno__first_name}} {{a.idAlumno__last_name}}, {{a.idAlumno__names}}
          </td>
                <td><input autofocus class="form-control "  onblur="nota(this,{{a.id}},'primerapractica')" type="number" value="{{a.primerapractica }}"></td>
                <td><input class="form-control " onblur="nota(this,{{a.id}},'segundapractica')" type="number" value="{{a.segundapractica }}"></td>
                <td><input class="form-control " onblur="nota(this,{{a.id}},'primerparcial')" type="number" value="{{a.primerparcial }}"></td>
                <td><input class="form-control " onblur="nota(this,{{a.id}},'segundoparcial')" type="number" value="{{a.segundoparcial }}"></td>
                <td><input class="form-control " onblur="nota(this,{{a.id}},'trabajos')"type="number" value="{{a.trabajos }}"></td>
                <td>{{a.notafinal|floatformat }}</td>

      </tr>
    {% endfor %}
    </tbody>
</table>
<script>
    function nota(t,id,n){
        no = $(t).val();

        if (no!="" && no>=0 && no<=20) {
            $.get("gestionasignatura/nota", {'id': id, 'nota': no, 'n': n}).done(function (d) {
                noti("success", d);
                traemedatos('gestionasignatura/evaluacion?id=' + {{idd}});
            });
        }else{
            $(t).val(0);
            noti("error", "mayor de 0 y menor o igual a 20");
        }
    }
</script>

apps/appAsignaturaDocente/templates/formularioClase.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">{{ tipo }} CLASE</h4>
</div>
<form action="POST" idd="{{ idd }}" onsubmit="reClase(this);return false" >
    <div class="modal-body">
            {% csrf_token %}
            {{ formulario.idAula.label_tag }}
            {{ formulario.idAula }}<br>

            {{ formulario.Tema.label_tag }}
            {{ formulario.Tema }}<br>

            {{ formulario.Descripcion.label_tag }}
            {{ formulario.Descripcion }}<br>

            {{ formulario.fecha.label_tag }}
            {{ formulario.fecha }}

            <input type="hidden" value="{{iddoc}}" id="id_idDocentexAsignatura" name="idDocentexAsignatura"/>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="submit"class="btn btn-primary">{{ tipo }}</button>

    </div>
</form>

<script>
    $("select").addClass("form-control input-sm");
    function reClase(t){
        idd = $(t).attr('idd');
        form= $(t).serialize();

        if (idd){
            u = "registro/Clase/update";
        }else{
            u = "gestionasignatura/addClase";
        }
          $.post(u,form+"&idd="+idd, function(data){
                    unblock_form();
                }).fail(function(resp) {
                unblock_form();
                var errors = JSON.parse(resp.responseText);
                console.log(resp);
                for (e in errors) {
                    var id = '#id_' + e;
                    $(id).after(errors[e]);
                }
                }).done(function(g){
                    $('#modal-8').modal('hide');
                    traemedatos('gestionasignatura/listadeclases?id='+{{iddoc}});
                    noti("success",g);
                });
        return false;
    }
</script>

apps/appAsignaturaDocente/templates/listaasistencia.html
<i class="puntero fa fa-arrow-left "
   onclick="traemedatos('gestionasignatura/listadeclases?id={{idc}}')"
   style="color: red">Atras</i>
<b>
    <h2 align="center"> Lista de Asistencias</h2>
</b>

<table class="table table-condensed">
    <thead>
      <tr>
        <th>N°</th>
        <th>Código</th>
        <th>Apellidos y Nombres</th>
      </tr>
    </thead>
    <tbody>
    {% for a in asistencia %}
      <tr>
          <td>{{forloop.counter}}</td>
          <td>
              {{a.idmatriculados__idAlumno__dni}}
          </td>
          <td>
              {{a.idmatriculados__idAlumno__first_name}} {{a.idmatriculados__idAlumno__last_name}}, {{a.idmatriculados__idAlumno__names}}
          </td>
      </tr>
    {% endfor %}
    </tbody>
</table>

apps/appAsignaturaDocente/templates/listadeclases.html
<i class="puntero fa fa-arrow-left "
   onclick="traemedatos('gestionasignatura/listaAsignatura')"
   style="color: red">Atras</i>
<b>
    <h2 align="center" style="color: #00b19b"> Lista de Clases y lista de asistencia de alumnos por clases </h2>
</b>
<i style="color: #00a792">AGREGAR CLASE
</i><br>
<i class="fa fa-plus-square fa-3x puntero" style="color: #00a792" onclick="add()"></i><br>
<table class="table table-condensed">
    <thead>
      <tr>
        <th>N°</th>
        <th>Tema</th>
        <th>Descripción</th>
        <th>Fecha</th>
        <th>Aula</th>
        <th>Ver Asistencia</th>
      </tr>
    </thead>
    <tbody>
    {% for a in clases %}
      <tr>
          <td>{{forloop.counter}}</td>
          <td>
              {{a.Tema}}
          </td>
          <td>
              {{a.Descripcion}}
          </td>
          <td>
              {{a.fecha}}
          </td>
          <td>
              {{a.idAula__Descripcion}}
          </td>
          <td>
              <i class="puntero fa fa-play-circle" style="color: #00b19b" onclick="verasistencia({{a.id}})"></i>
          </td>

      </tr>
    {% endfor %}
    </tbody>
</table>
<div class="modal" data-easein="perspectiveRightIn" id="modal-8" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
     <div class="modal-dialog" role="document">
         <div class="modal-content"></div>
     </div>
</div>
{% load static %}
<script src="{% static 'js/appSecurity/base.js' %}"></script>
<script src="{% static 'js/app_listas/listas.js' %}"></script>
<script>
    function  verasistencia(id){
        $.get("gestionasignatura/asistencia?id="+id+"&idc="+{{iddoc}}).done(function(r){
            $("#resultados").empty().html(r);
        });
    }

    function add(){
        $.get("gestionasignatura/addClase?iddoc="+{{iddoc}},function(d){
            $("#modal-8 .modal-content").empty().html(d);
            $('#modal-8').modal('show');
        });
    }

</script>

apps/appAsignaturaDocente/templates/listadocentesSemestre.html
<h3 style="color: #00a792">LISTA DEL DOCENTE DEL SEMESTRE {{ semestre.0.Anio_semestre }}: </h3><br>

<table class="table table-hover" role="grid">
    <thead>
    <tr>
        <th>N°</th>
        <th>Nombres y Apellidos</th>
        <th>Asignatura</th>
    </tr>
    </thead>
<tbody>
    {% for foo in docentes %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                {{ foo.idDocente__Nombre|title }} {{ foo.idDocente__Apellidos|title }}
            </td>
            <td>
                <i  onclick="verasignatura({{ foo.idDocente_id }})" style="color: #00a792" class="puntero fa fa-arrow-right fa-2x">ver</i>
            </td>

        </tr>



    {% endfor %}

</tbody>
</table>

<script>
    function verasignatura(id){
        $.get("asignaturadocente/asignaturaxdocente/listarasignaturas",{'iddocente':id}).done(
           function(d){
               $("#resultados").empty().html(d);

           }
        );

    }
</script>

apps/appAsignaturaDocente/templates/listaraAsignatura.html
<i class="puntero fa fa-arrow-left fa-2x" onclick="traemedatos('asignaturadocente/asignaturaxdocente/listardocentes?idsemestre={{ ids }}')" style="color: red">Atras</i>
<h2 style="color: #00a792">Lista de Asignatura del docente: {{ nombredocente.0.Nombre }} {{ nombredocente.0.Apellidos }}</h2>
<style>
    .trhover:hover{
        background-color: #00a792;
        cursor: pointer;
    }
</style>

{% if asignaturas %}
<table class="table table-condensed">
    <thead>
    <tr>
        <td width="60px">Agregar</td>
        <td>N°</td>
        <td>Nombre</td>
        <td>Créditos</td>
        <td></td>
    </tr>
    </thead>
    <tbody>
    {% for d in asignaturas %}
        <tr                 {% for s in DocentexAsignatura %}
                        {% if d.id == s.idAsignatura_id %}
                           class="info"
                        {% endif %}

                {% endfor %}>
            <td>
                <i class="fa fa-plus puntero" style="color: #00a792"  onclick="add({{ d.id }},{{ semestredocente}},{{ nombredocente.0.id }},{{ ids }})"></i>
            </td>
            <td width="50px">{{ forloop.counter }}</td>
            <td width="200px" class="trhover" onclick="add({{ d.id }},{{ semestredocente}},{{ nombredocente.0.id }},{{ ids }})">
                {{ d.Nombre }}
            </td>
            <td>{{ d.Creditos }}</td>
            <td>
                {% for s in DocentexAsignatura %}
                        {% if d.id == s.idAsignatura_id %}
                            <i onclick="eliminar({{ s.id }},{{ semestredocente}},{{ nombredocente.0.id }},{{ ids }})" class="puntero fa fa-trash-o fa-2x" style="color: red"></i>
                        {% endif %}

                {% endfor %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endif %}
{% load static %}
<script src="{% static 'js/appSecurity/base.js' %}"></script>
<script src="{% static 'js/app_listas/listas.js' %}"></script>
<script>
        function verasignatura(id,idsd){
        $.get("asignaturadocente/asignaturaxdocente/listarasignaturas$",{'id':id,'idsemestredocente':idsd}).done(
           function(d){
               $("#resultados").empty().html(d);
           }
        );

    }
            function add(ida,idsd,idd,ids){
                $.post("asignaturadocente/asignaturaxdocente/listarasignaturas",{'csrfmiddlewaretoken':"{{ csrf_token }}",'idasignatura':ida,'idsemestredocente':idsd}).done(function(d){
                    noti("success", d);
                    traemedatos('asignaturadocente/asignaturaxdocente/listarasignaturas?ids='+ids+'&iddocente='+idd+'&id='+idsd);
                }).fail(function(resp) {
                    var errors = resp.responseText;
                    noti("error", errors);
            });
            }

            function eliminar(id,idsd,idd,ids){
                $.get("asignaturadocente/SemestrexDocente/eliminar",{'iddd':id}).done(function(d) {
                    noti("error", d);
                    traemedatos('asignaturadocente/asignaturaxdocente/listarasignaturas?id='+idsd+'&ids='+ids+'&iddocente='+idd);
                });
            }

</script>