apps/security/urls.py
from django.conf.urls import url
from django.contrib.auth.views import password_change,password_change_done
from apps.security.views.view_permission import permissionView, CambiarEstado, CambiarEstadoTotal
from apps.security.views.view_profile import deleteprofile ,profiles,editprofile
from apps.security.views.view_module import module, deletemodule,submodule,updatemodule,editamh, fonts

from apps.core.error import error404
from apps.security.views.view_account import cuentita, cuentaedi, datoscuenta,fotoperfil, guardaperfil, register_users, usuariosCompletado, list_users, update_users, about_users, deleteuser
from apps.security.views.view_login import login,LogOut, register
from apps.security.views.view_security import index



urlpatterns = [
    url(r'^login/$',login.as_view()),
    url(r'^register/$',register.as_view()),
    url(r'^salir/$', LogOut, name="cerrarsesion"),
    url(r'^fotoprofile/$', fotoperfil ),
    url(r'^$', index, name="index" ),
    url(r'^error404/$', error404.as_view(), name="error404" ),

    #perfiles
    url(r'^security/profile/$', profiles ),
    url(r'^security/profile/frmp/$', editprofile ),
    url(r'^security/profile/delete/(?P<id>\d+)/$', deleteprofile),

    #permission
    url(r'^security/permission/$', permissionView),
    url(r'^security/permission/CambiarEstado/$', CambiarEstado),
    url(r'^security/permission/CambiarEstadoTotal/$', CambiarEstadoTotal),

    #cuenta
    url(r'^security/guardaprofile$', guardaperfil),
    url(r'^security/datoscuenta$', datoscuenta),
    url(r'^password$', password_change, {'template_name': 'contra_usu.html'}),
    url(r'^password-hecho$', password_change_done, {'template_name': 'password-hecho.html'},name='password_change_done'),
    url(r'^security/cuenta$', cuentita, name="editcuenta"),
    url(r'^security/cuedi/$', cuentaedi ),

    #modules
    url(r'^security/modules/$', module),
    url(r'^security/modules/delete/(?P<id>\d+)/$', deletemodule),
    url(r'^security/modules/edit/(?P<id>\d+)/$', updatemodule),
    url(r'^security/submodules/(?P<id>\d+)/$', submodule ),
    url(r'^security/modules/fonts/$', fonts ),
    url(r'^security/modules/editmh/$', editamh ),

    #users
    #url(r'^security/guardarpadres$', guardarpadre ),
    url(r'^security/usuarios/add/$', register_users.as_view()),
    url(r'^security/usuarios/(?P<pk>[0-9]+)/$', update_users.as_view()),
    url(r'^security/usuarios/view/$', about_users.as_view()),
    url(r'^security/usuarios$', list_users.as_view()),
    url(r'^security/usuarios/delete/(?P<id>\d+)/$', deleteuser),
    url(r'^security/usuarios/completado$', usuariosCompletado, name="user-completado" ),

]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.security.urls')),
    url(r'^', include('apps.Sistema_Aplicacion.urls')),
    url(r'^', include('apps.appmatricula.urls')),
    url(r'^', include('apps.appAsignaturaDocente.urls')),
    url(r'^', include('apps.appReporte.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/security/models.py
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin, Group
)
from django.core import validators
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe

from apps.core.core import TimeStampedModel
class icons(models.Model):
    description = models.CharField(max_length=100)
    clase = models.CharField(max_length=100)

    def __str__(self):
        return mark_safe("<li class='" + self.clase + "'><li> " + self.description)

class modules(TimeStampedModel):
    description = models.CharField(max_length=50)
    father = models.IntegerField(default=0)
    url = models.CharField(max_length=150)
    icon = models.ForeignKey(icons, null=True, related_name='idicon')
    def __str__(self):
        return self.description
class profile(TimeStampedModel):
    description = models.CharField(max_length=50)
    module      = models.ManyToManyField(modules, through="detail_permission_profile_modules")

    def __str__(self):
        return self.description

class detail_permission_profile_modules(TimeStampedModel):
    idprofile = models.ForeignKey(profile)
    idmodules = models.ForeignKey(modules)
    See = models.BooleanField(default=True)
    Search = models.BooleanField(default=True)
    Add = models.BooleanField(default=True)
    Update = models.BooleanField(default=True)
    Delete = models.BooleanField(default=True)
    Print = models.BooleanField(default=True)
    Export = models.BooleanField(default=True)
    Import = models.BooleanField(default=True)



class MyUserManager(BaseUserManager):
    def create_user(self, email, username, dni, password=None):
        if not email:
            raise ValueError('El usuario tiene una dirección email incorrecta')

        if not dni:
            raise ValueError('El usuario tiene dni incorrecta')

        user = self.model(
            email    = self.normalize_email(email),
            username = username,
            dni      = dni,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, dni, password):
        
        user = self.create_user(email,
            password = password,
            username = username,
            dni      = dni
        )
        user.is_admin = True
        user.save(using=self._db)
        return user



class Users(AbstractBaseUser, PermissionsMixin, TimeStampedModel ):
    username = models.CharField(
        ('Usuario'),
        max_length  = 30,
        unique      = True,
        help_text   = ('Requiere: 30 carácteres o menos. Letras, digitos y  @/./+/-/_ sólo.'),
        validators  = [
            validators.RegexValidator(
                r'^[\w.@+-]+$',
               ('Ingrese un usuario válido. Este valor solo podrá contener '
                 'Letras, Números ' 'and @/./+/-/_ Carácteres.')
            ),
        ],
        error_messages={
            'unique': ("Ya existe usuario con ese nombre"),
        },
    )
    names            = models.CharField(max_length=50,null=True, verbose_name='Nombres')
    first_name       = models.CharField(max_length=50,null=True, verbose_name='Apellido Paterno')
    last_name        = models.CharField(max_length=50,null=True, verbose_name='Apellido Materno')
    dni              = models.CharField(
        max_length=8,
        unique=True,
        help_text=('DNI Requiere: 8 carácteres obligatorios'),
        validators=[
            validators.RegexValidator(
                r'^[\w.@+-]+$',
                ('Ingrese un dni válido. Este valor solo podrá contener '
                 'Números' 'de 8 Dígitos.')
            ),
        ],
        error_messages={
            'unique': ("Ya existe dni, probar con otro"),
        },
    )
    Sex = (
        ('f', 'Femenino'),
        ('m', 'Masculino'),
    )

    email            = models.EmailField(verbose_name='Dirección de email',max_length=255, unique=True, blank=True, null=True)
    date_birth       = models.DateField(null=True, verbose_name='Fecha de Cumpleaños')
    foto             = models.ImageField(max_length=500, upload_to='fotoperfil', null=True)
    cellphone        = models.CharField(max_length=100, null=True, verbose_name='Celular')
    telephone        = models.CharField(max_length=100, null=True)
    address          = models.CharField(max_length=200,null=True)
    work_experiencie = models.CharField(max_length=30, null=True)
    sex              = models.CharField(max_length=1, choices=Sex)
    password_default = models.CharField(max_length=15, null=True)

    profiles = models.ManyToManyField(profile, blank=True)

    is_staff = models.BooleanField(
        ('staff status'),
        default=False,
        help_text=('Indica si el usuario puede iniciar sesión en este sitio de administración.'),
    )
    is_active = models.BooleanField(
        ('active'),
        default=True,
        help_text=(
            'Designa si el usuario debe ser tratado como activo. '
            'Seleccionarla en lugar de eliminar las cuentas .'
        ),
    )
    date_joined = models.DateTimeField(('fecha de Inscripción'), default=timezone.now)

    is_admin         = models.BooleanField(default=False)
    objects          = MyUserManager()

    USERNAME_FIELD   = 'username'
    REQUIRED_FIELDS  = ['dni','email']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.username

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

apps/security/views/view_account.py
from django.shortcuts import render, HttpResponse,get_object_or_404
from registration.backends.hmac.views import RegistrationView
from django.views.generic import TemplateView, UpdateView
from django.core.mail import send_mail
from django.http import HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy

from rest_framework.renderers import JSONRenderer,TemplateHTMLRenderer
from rest_framework.decorators import api_view, renderer_classes, permission_classes
import json, string, random
#esto es par
from django.contrib.auth import get_user_model
User = get_user_model()

from apps.security.serializers import cuenseria
from rest_framework import generics, permissions
from apps.security.models import Users, profile
from apps.security.forms import cueform, formFoto,UsuarioCreationForm

@login_required(login_url='login/')
def cuentita(m):
    return render(m, 'cuenta.html')

@login_required(login_url='login/')
@api_view(['GET','POST'])
@permission_classes((permissions.AllowAny,))
@renderer_classes((TemplateHTMLRenderer, JSONRenderer))
def cuentaedi(q):
    a = q.user.id
    fa=get_object_or_404(Users,pk=int(a))
    f=cueform(instance=fa)
    return render(q, "formcuenta.html", {"f":f})

def datoscuenta(q):
    return render(q, "datoscuenta.html")
#contraseña aleatoria
def id_generator(size=8, chars=string.ascii_uppercase + string.digits + string.punctuation ):
    return ''.join(random.choice(chars) for _ in range(size))

class list_users(LoginRequiredMixin, TemplateView):
    login_url= reverse_lazy('error404')
    template_name = "t_users.html"
    def get_context_data(self, **kwargs):
        context = super(list_users, self).get_context_data(**kwargs)
        u = Users.objects.filter(status=True)
        #p = Users.profile.all
        #print(p)
        context['users'] = u
        #context['profile'] = p

        return context

class about_users(LoginRequiredMixin, TemplateView):
    login_url= reverse_lazy('error404')
    template_name = "about_user.html"
    def get_context_data(self, **kwargs):
        context = super(about_users, self).get_context_data(**kwargs)
        u = Users.objects.filter(status=True, id= self.request.GET.get("id"))[:1]
        context['users'] = u

        return context

import datetime
@login_required(login_url='login/')
def deleteuser(em, id):
    e = Users.objects.get(pk = id)
    e.status = False
    e.save()
    return HttpResponse("eliminado correctamente")

class register_users(LoginRequiredMixin, RegistrationView):
    login_url= reverse_lazy('error404')
    form_class  = UsuarioCreationForm
    template_name = "form_user.html"

    def get_context_data(self, **kwargs):
        context = super(register_users, self).get_context_data(**kwargs)
        context['name'] = 'Registrar'

        return context
    def get_success_url(self, user):
        return ('/security/usuarios/completado', (), {})

    def form_invalid(self, form):
        ee = {}
        if form.errors:
            for i in form.errors:
                e = form.errors[i]
                ee[i] = str(e)
        return HttpResponseBadRequest(json.dumps(ee))

    def create_inactive_user(self, form):
        p = id_generator()
        new_user                   = form.save(commit=False)
        new_user.is_active         = True
        new_user.username          = form.cleaned_data["dni"]
        new_user.password_default  = p
        new_user.set_password(p)
        new_user.save()
        if  form.cleaned_data["email"]:
            send_mail(
                'SisAlumno le da la bienvenida!',
                'su usuario es: .'+str(form.cleaned_data["dni"])+' y su contraseña es: '+str(p),
                'sisalumno@gmail.com',
                [form.cleaned_data["email"]],
                fail_silently=False,
            )

        for i in self.request.POST.getlist('profiles'):
            new_user.profiles.add(int(i))

        return new_user

class update_users(LoginRequiredMixin, UpdateView):
    login_url= reverse_lazy('error404')
    template_name = "form_user.html"
    model = Users
    form_class  = UsuarioCreationForm
    exclude = ('password1','password1','email',)
    success_url = reverse_lazy('user-completado')

    def get_context_data(self, **kwargs):
        context = super(update_users, self).get_context_data(**kwargs)
        context['name'] = 'Actualizar'
        return context



    def form_invalid(self, form):
        ee = {}
        if form.errors:
            for i in form.errors:
                e = form.errors[i]
                ee[i] = str(e)
        return HttpResponseBadRequest(json.dumps(ee))



def fotoperfil(r):
    a     = get_object_or_404(Users, pk=r.user.id)
    formu = formFoto(r.POST,r.FILES, instance=a)
    print(formu)
    if formu.is_valid():
        formu.save()
    return HttpResponse("foto guardada correctamente")

def usuario(r):
    return render(r, "usuario.html")

def guardaperfil(r):
    a=get_object_or_404(Users, pk=r.user.id)
    form=cueform(r.POST,instance=a)
    if form.is_valid():
        form.save()
        return HttpResponse("guardado")
    else:
        if r.is_ajax():
            ee = {}
            if form.errors:
                for i in form.errors:
                    e = form.errors[i]
                    ee[i] = str(e)

            return HttpResponseBadRequest(json.dumps(ee))

def usuariosCompletado(r):
    return HttpResponse("ok registrado")

apps/security/views/view_login.py
from registration.backends.hmac.views import RegistrationView
from django.http import HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
from django.contrib import auth


from django.http import HttpResponseRedirect
from django.views.generic import FormView
from django.core.urlresolvers import reverse_lazy

from apps.security.forms import LoginForm, UsersRegisterForm
import json

class login(FormView):
    form_class  = LoginForm
    template_name = "login.html"
    success_url = reverse_lazy('index')
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(login, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        username = self.request.POST['username']
        password = self.request.POST['password']
        user = authenticate(username=username, password=password)
        auth.login(self.request, user)
        return super(login, self).form_valid(form)

    def form_invalid(self, form):
        ee = {}
        if form.errors:
            for i in form.errors:
                e = form.errors[i]
                ee[i] = str(e)
        return HttpResponseBadRequest(json.dumps(ee))

def LogOut(request):
    logout(request)
    return HttpResponseRedirect('/')

class register(RegistrationView):
    form_class  = UsersRegisterForm
    template_name = "form_regis_user.html"

    def get_success_url(self, user):
        return ('/security/usuarios/completado', (), {})

    def form_invalid(self, form):
        ee = {}
        if form.errors:
            for i in form.errors:
                e = form.errors[i]
                ee[i] = str(e)
        return HttpResponseBadRequest(json.dumps(ee))

    def create_inactive_user(self, form):

        new_user                   = form.save(commit=False)
        new_user.is_active         = True
        new_user.username          = form.cleaned_data["username"]
        new_user.email             = form.cleaned_data["email"]
        new_user.password_default  = form.cleaned_data["password2"]
        new_user.set_password(form.cleaned_data["password2"])
        new_user.save()

        for i in self.request.POST.getlist('profiles'):
            new_user.profiles.add(int(i))

        return new_user

apps/security/templates/base.html
<!DOCTYPE html>
<html lang="es"> 
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static from staticfiles %}
    <link rel="icon" type="image/png" href="{{ MEDIA_URL }}/img/icons/favicon1.png">
        <meta name="author" content="">
        <meta name="keywords" content="">
        <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    {% block css %}

    {% endblock %}

</head>

<body>

    {% block contenido %} 
    {% endblock %}

    <script type="text/javascript" src="{% static 'js/demo-skin.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/js-core.js.pagespeed.jm.NS0ql0YgTp.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/jquery-cript.js' %}"></script>
    <!-- jquery cript -->
    <script>eval(mod_pagespeed_19WID9$3F8);</script>


    {% block js %}
    
    {% endblock %}

</body>
</html>

apps/security/templates/contra_usu.html
{% load static %}
 <link rel="stylesheet" type="text/css" href="{% static 'css/estilosadmin.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
<style>
    .errorlist{
        color: red;
    }
</style>
<form action="" method="post">{% csrf_token %}

<div class="form-group">
    {{ form.old_password.label_tag }} {{ form.old_password }}
    {{ form.old_password.errors }}
</div>

<div class="form-group">
    {{ form.new_password1.label_tag }} {{ form.new_password1 }}
    {{ form.new_password1.errors }}

</div>

<div class="form-group">
    {{ form.new_password2.label_tag }} {{ form.new_password2 }}
    {{ form.new_password2.errors }}
    {% if form.new_password2.help_text %}
    <p class="help">{{ form.new_password2.help_text }}</p>
    {% endif %}
</div>
    <script type="text/javascript" src="{% static 'js/js-core.js.pagespeed.jm.NS0ql0YgTp.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/jquery-cript.js' %}"></script>
    <!-- jquery cript -->
    <script>eval(mod_pagespeed_19WID9$3F8);</script>
<script type="text/javascript">document.getElementById("id_old_password").focus();</script>
<script>
    $("input").addClass("form-control input-sm");
</script>
<div class="submit-row">
    <input type="submit" class="btn btn-sm btn-primary pull-left m-t-n-xs"value="cambiar" class="default" />
</div>

apps/security/templates/cuenta.html
{% load static from  staticfiles %}

    <style>
        .errorlist {
            color: red;
        }
        li{
            list-style: none;
        }
    </style>
<link href="{% static 'css/fotoperfil.css' %}" rel="stylesheet"/>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
    <br>
        <ol class="breadcrumb">
            <li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Perfil</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>

<div class="row animated fadeInRight">
    <div class="col-md-4">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Perfil</h5>
                        </div>
                        <div>
                            <div class="ibox-content no-padding border-left-right">
                                <form method="post" enctype="multipart/form-data" id="formularioImg">
                                    {% csrf_token %}
                                    <div class="perfilI">
                                        <input type="file"  id="imgInp" accept="image/*" name="foto" value="" placeholder="">
                                        <img id="img" width="200px" height="200px" class="vista img-responsive di" src="" alt="">
                                        {% if user.foto %}
                                             <img id="mos_img" alt="image" width="200px" class="img-responsive re" src="{{MEDIA_URL}}{{user.foto}}">
                                        {% else %}
                                            <img alt="image" width="200px" class="img-responsive re" src="{{MEDIA_URL}}fotoperfil/miuser.jpg">
                                        {% endif %}
                                        <a href="#" >
                                            <i style="display:none" class="fa fa-pencil fa-2x pen re"></i>
                                        </a>                                   
                                    </div>
                                </form>
                                <a href="#">
                                        <i onclick="guardarI('fotoprofile/')" style="color:green" class="fa fa-check fa-2x di bora"></i>
                                </a>
                                <a href="#">
                                        <i onclick="cancel()" style="color:red" class="fa fa-ban fa-2x di xx bora"></i>
                                </a>                                                                   

                                
                                
                            </div>
                            <div id="impri" class="ibox-content profile-content">
                                
                            </div>
                    </div>
                </div>
                    </div>
                <div class="col-md-8">
                    <div class="ibox float-e-margins">

                        <div class="ibox-content his">
                                <div class="example-box-wrapper">
        <ul class="list-group row list-group-icons">
            <li class="col-md-3" onclick="edi()">
                <a href="#tab-example-1" data-toggle="tab" class="list-group-item">
                    <i class="glyph-icon font-blue icon-bullhorn"></i>
                    Editar Información
                </a>
            </li>
            <li class="col-md-3" onclick="contra()">
                <a href="#tab-example-1" data-toggle="tab" class="list-group-item">
                    <i class="glyph-icon icon-dashboard"></i>
                    Cambiar contraseña
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade" id="tab-example-1">
                <div class="row" id="editar">
                    
                </div>
            </div>
        </div>
    </div>
                        </div>
                    </div>

                </div>
</div>
<script type="text/template"  id="mostrar">
    
                                
</script>    
<script src="{%static 'js/fotoperfil.js' %}"></script>

apps/security/templates/datoscuenta.html
<h4><strong>{{user.username|title}} </strong></h4>
<p><i class="fa fa-map-marker"></i> NOMBRE: {{user.names}}</p>
<p><i class="fa fa-map-marker"></i> APELLIDO: {{user.first_name}} {{user.last_name}} </p>
<p><i class="fa fa-map-marker"></i> DNI: {{user.dni}}</p>
<p><i class="fa fa-map-marker"></i> TELÉFONO: {{user.telephone}}</p>
<p><i class="fa fa-map-marker"></i> Dirección: {{user.address}}</p>
<p><i class="fa fa-map-marker"></i> fecha de Inscripción: <br> {{user.date_joined}}</p>

apps/security/templates/formcuenta.html
<div class="content-box" >
<form action="" id="form_gurcuenta" method="POST" accept-charset="utf-8">
{% csrf_token %}
{{f}}
</form>
<div class="col-md-6">
    <a href="#editar_info" onclick="guardar_perfil()" class="btn btn-primary btn-sm btn-block">Guardar</a>
</div>
</div>

apps/security/templates/frm_profile.html
    <h4 align="center">{{title}} PERFIL</h4>
    <form action="" id = "Formprofile" method="POST" accept-charset="utf-8">
        {% csrf_token %}
        <div>
        {{frm}}
        </div>
        <button type="button" onclick="registerprofile(this)" class="btn btn-alt btn-hover btn-info" idprofile="">
            <span>{{btn}} </span>
            <i class="glyph-icon icon-arrow-right"></i>
        </button>
    </form>

apps/security/templates/password-hecho.html
<h3>Su Contraseña fue cambiada correctamente</h3>

apps/security/templates/t_module.html
{% load static %}
<link href="{%static 'css/select2/select2.min.css' %}" rel="stylesheet" />

<!--registrar sub module-->
<div id="m">
    <h2 align="center">Registrar Nuevo Módulo</h2><br>
    <form  id = "Formmodule" align="center" method="POST" accept-charset="utf-8" class="form-inline" >
        {% csrf_token %}
          <div class="form-group">
              <label for="id_description">Descripción:</label>
              {{formulario.description}}
          </div>

          <div class="form-group">
              <label for="id_icon">Icono:</label> 
              <select  class="form-control module"  id="id_icon" style="width: 200px" name="icon"></select>
          </div>
          
          <input type="button"  id="registermodule" value="Agregar" class="btn btn-primary">
         
    </form><br><br>

    <!-- reistrar-->
            <div class="col-md-6" style="text-align:center;">
             <label> MÓDULO</label>
                <div id="modul" class="">
                <table class="table table-inverse">
                    <tbody id="m1">

                   </tbody>
                </table>
                </div>
          </div>

          <div class="col-md-6" style="text-align:center;">
             <label> SUBMÓDULO</label>
               <div id="submodul">
                   <table class="table table-inverse">
                      <tbody id="sub">          

                      </tbody>
                    </table>
               </div>
          </div>


          <!-- Modal -->
<div id="myModal" ></div>
<script type="text/templates" id="tFormMod">
        <form id="formM">
            {% csrf_token %}
            <input type='hidden' name='father' value='<%= id %>'/>
            <% _.each(data, function(i,k){   %>
            <label>Descripción:</label>
            <input id='id_description' type='text' class='form-control' value='<%= i.description.toLowerCase() %>' name='description'>
            <label>Icono:</label><br>
            <select  id='id_icon' class='form-control moduleB' style='width:100%'  name='icon'>
                <option value='<%= i.icon.id %>'></option>
            </select><br>
            <% }) %>
        </form>
</script>
<script type="text/templates" id="tFormSubM">
        <form id="formSubM">
            {% csrf_token %}
                <input type='hidden' name='father' value='<%= id %>'/>
                <% if (data != null){ _.each(data, function(i,k){   %>
                <label>Descripción:</label>
                <input type='text' id='id_description' value='<%= i.description %>'
                       class='form-control' onkeyup='kdes(this,"<%= de.toLowerCase() %>")' name='description'/>
                <label>Icono:</label>
                <br>
                <select  class='form-control moduleA' id='id_icon' style='width:100%'  name='icon'>
                    <option value='<%= i.icon.id %>'><%= i.icon.clase %></option>
                </select>
                <br>
                <div >
                    <label>nombre de Url</label>
                    <input name='url' id='url' type='text' class='form-control' value='<%= i.url %>/' disabled>
                    <input name='url' id='url' type='hidden'  value='<%= i.url %>/'>
                </div>
            <% }) }else{ %>
                <label>Descripción:</label>
                <input type='text' id='id_description' value=''
                       class='form-control' onkeyup='kdes(this,"<%= de.toLowerCase() %>")' name='description'/>
                <label>Icono:</label>
                <br>
                <select  class='form-control moduleA' id='id_icon' style='width:100%'  name='icon'>
                </select>
                <br>
                <div >
                    <label>nombre de Url</label>
                    <input name='url' id='url' type='text' class='form-control' value='<%= de.toLowerCase()%>/' disabled>
                </div>
            <% } %>
        </form>
</script>

<script type="text/templates" id="tmodule">
    <% _.each(data, function(i,k){ if (i.father==0){  %>
        <tr>
            <td><%= k+1 %></td>
            <td>
                <i class="<%= i.icon.clase %>"/>
            </td>
            <td style="text-transform:uppercase;">
                <%= i.description %>
            </td>
            <td>
                <a href="#" onclick="UpdateMod(<%= i.id %>)">
                    <i class="fa fa-pencil-square-o"></i>
                </a>
            </td>
            <td>
                <a href="#"  onclick="DeleteMod(<%= i.id %>)">
                    <i class="fa fa-trash"></i>
                </a>
            </td>
            <td>
                <a href="#"  onclick="SeeSubMod(<%= i.id %>,'<%= i.description %>')">
                    <i class="fa fa-share"></i>
                </a>
            </td>
        </tr>
    <% } }) %>
</script>


<script type="text/template" id="tsubmodule">

    <% _.each(data, function(i,k){ %>
    <tr>
        <td><%= k+1%></td>
        <td>
            <i class="<%= i.icon.clase %>"/>
        </td>
        <td style="text-align:left;"><%= i.description %></td>
        <td>
            <a href="#" onclick="updateSubM(<%= i.id %>,'<%= d %>','<%= p %>')">
                <i class="fa fa-pencil-square-o"></i>
            </a>
        </td>
        <td>
            <a href="#" onclick="deleteSubMod(<%= i.id %>,'<%= d %>','<%= p %>')">
                <i class="fa fa-trash"></i>
            </a>
        </td>
    </tr>
    <% }) %>

</script>

<script src="{% static 'js/appSecurity/base.js' %}"></script>
<script src="{% static 'js/appSecurity/module.js' %}"></script>
<script src="{% static 'js/appSecurity/submodule.js' %}"></script>